#!/usr/bin/env bash
# Create host directories
# Create host directories with sudo
[ ! -d /home/steam/game-servers/miscreated ] && sudo mkdir -p /home/steam/game-servers/miscreated
[ ! -d /home/steam/game-servers/miscreated/DatabaseBackups ] && sudo mkdir -p /home/steam/game-servers/miscreated/DatabaseBackups
[ ! -d /home/steam/game-servers/miscreated/logbackups ] && sudo mkdir -p /home/steam/game-servers/miscreated/logbackups
[ ! -d /home/steam/game-servers/miscreated/logs ] && sudo mkdir -p /home/steam/game-servers/miscreated/logs

# Ensure files exist with sudo
[ ! -f /home/steam/game-servers/miscreated/banned.xml ] && sudo touch /home/steam/game-servers/miscreated/banned.xml
[ ! -f /home/steam/game-servers/miscreated/hosting.cfg ] && sudo touch /home/steam/game-servers/miscreated/hosting.cfg
[ ! -f /home/steam/game-servers/miscreated/reservations.xml ] && sudo touch /home/steam/game-servers/miscreated/reservations.xml
[ ! -f /home/steam/game-servers/miscreated/whitelist.xml ] && sudo touch /home/steam/game-servers/miscreated/whitelist.xml

# Run Docker container
docker run -d --name "miscreated-server" \
    -p 64090:64090/udp \
    -p 64091:64091/udp \
    -p 64092:64092/udp \
    -p 64093:64093/udp \
    -p 64094:64094/tcp \
    --restart always \
    -v "/home/steam/game-servers/miscreated:/data" \
    -v "/home/steam/game-servers/miscreated/banned.xml:/app/banned.xml" \
    -v "/home/steam/game-servers/miscreated/DatabaseBackups:/app/DatabaseBackups" \
    -v "/home/steam/game-servers/miscreated/hosting.cfg:/app/hosting.cfg" \
    -v "/home/steam/game-servers/miscreated/logbackups:/logbackups" \
    -v "/home/steam/game-servers/miscreated/logs:/app/logs" \
    -v "/home/steam/game-servers/miscreated/reservations.xml:/app/reservations.xml" \
    -v "/home/steam/game-servers/miscreated/whitelist.xml:/app/whitelist.xml" \
    miscreated-server

#   -p $(( ${EXTERNAL_BASE_GAME_PORT} + ${SERVER_BASE_NUM} )):26900/tcp \
#   -p $(( ${EXTERNAL_BASE_GAME_PORT} + ${SERVER_BASE_NUM} )):26900/udp \
#   -p $(( ${EXTERNAL_BASE_GAME_PORT} + ${SERVER_BASE_NUM} + 1 )):26901/udp \
#   -p $(( ${EXTERNAL_BASE_GAME_PORT} + ${SERVER_BASE_NUM} + 2 )):26902/udp \
#   -p $(( ${EXTERNAL_BASE_WEB_PORT} + ${SERVER_BASE_WEB_NUM} )):8080/tcp \
#   -p $(( ${EXTERNAL_BASE_WEB_PORT} + ${SERVER_BASE_WEB_NUM} + 1 )):8081/tcp \
#   --name "${CONTAINER_NAME}" \
#   --user ${THIS_UID}:${THIS_GID} \
#   --restart always \
#   -v "${DATA_DIR}:/data" \
#   "${VOLUME_MOUNTS[@]}" \
#   -e UPDATE_GAME_SERVER=${UPDATE_GAME_SERVER} \
#   ${IMAGE_NAME}